### ISSUE TITLE
PHP fatal error after activating LoginShibboleth plugin in piwik

### ISSUE THREAD

**Issue by n0trax** [uniwue-rz/LoginShibboleth#1]
Hi,

if i activate the plugin, the piwik webinterface only shows a blank page and i get the following php error:

`PHP Fatal error:  Cannot declare class Piwik\\Plugins\\LoginShibboleth\\Menu, because the name is already in use in /var/www/piwik/plugins/ShibbolethLogin/Menu.php on line 0, referer: http://webdev/index.php?module=CorePluginsAdmin&action=plugins&idSite=1&period=day&date=yesterday&activated=&mode=admin&sort=`

I tested piwik 2.16.0 on debian jessie with php 5.6 and piwik 2.16.5 on ubuntu xenial with php 7.0 - same error on both systems.

The plugin was installed via Piwik Marketplace and i added the LoginShibboleth section to the config.ini.php.

Any ideas what i did wrong? Please let me know if you need some further information.

**Comment by pouyana** [comment]
There were several different factors involved here:
- There is a bug in php-opcache which make this not happen (https://bugs.php.net/bug.php?id=66773). It is fixed but not on my version of PHP :(.
- The name of the plugin in Marketplace does not match the Name of the class the plugin is using. I change this so that should solve your problem.
Greetings and thanks for the report.

Solved in: 69c5721fb8a87cf0ad1c424c1ae7d69b9ef6fa35
