### ISSUE TITLE
Call to undefined method error getHashTokenAuth()

### ISSUE THREAD

**Issue by n0trax** [uniwue-rz/LoginShibboleth#2]
Hi,

after installing version 1.1.10 i got the following error:
`Call to undefined method Piwik\\Plugins\\LoginShibboleth\\LoginShibbolethAuth::getHashTokenAuth()`

I tested piwik 2.16.0 on debian jessie with php 5.6 and piwik 2.16.5 on ubuntu xenial with php 7.0 - same error on both systems.

This time i installed the plugin via zip-Upload and via Marketplace...same result with both scenarios.

**Comment by pouyana** [comment]
This happens if you didn't set the Shibboleth setting right, to gain the superuser access through Shibboleth.
Anyway if no Shibboleth $_SERVER variables are available it should fallback to Piwik Login, I updated to the last Piwik/Plugins/Login/Auth implementation (e16673907508d3e345e291209f164f321206441e) and tested it. Now you can login with piwik superUser account.
Thanks for the report

**Comment by n0trax** [comment]
Thx for your fast response. With version 1.1.12 the plugin is working fine :-)

But i had some trouble getting it running, IMHO the documentation of the installation process could be
a little bit more specific. Also I had some error messages after the activation of the plugin. I will make a PR / Issue for that tomorrow or next week.

Do you know the Shibboleth plugin for wordpress? I don't know if it's possible with piwik, but maybe you can implement the login behavior in a similar way.

**Comment by pouyana** [comment]
Fixed
